<a href="https://colab.research.google.com/github/sakibchowdhury131/railcop/blob/main/basic_MLP_with_CONV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q tensorflow==2.2.0

     |████████████████████████████████| 516.2 MB 3.7 kB/s 
     |████████████████████████████████| 3.0 MB 53.2 MB/s 
     |████████████████████████████████| 2.9 MB 44.0 MB/s 
     |████████████████████████████████| 454 kB 27.7 MB/s 


In [ ]:
import numpy as np
np.random.seed(1)

import tensorflow as tf
tf.random.set_seed(1)

In [ ]:
import os
from tensorflow import keras
import matplotlib.pyplot as plt
import math
import pandas as pd

In [ ]:
label0 = pd.read_csv('/content/drive/MyDrive/RailCop/New Files/Sakib/data/train_7_label0.csv')
label1 = pd.read_csv('/content/drive/MyDrive/RailCop/New Files/Sakib/data/train_7_label1.csv')
print(label0)

      Sensor1  ...  Sensor1+Sensor2+Sensor3+Sensor4
0          21  ...                               31
1          11  ...                               21
2          11  ...                               20
3          12  ...                               22
4          10  ...                               19
...       ...  ...                              ...
5295       10  ...                               20
5296       11  ...                               22
5297       12  ...                               23
5298       10  ...                               19
5299        9  ...                               18

[5300 rows x 15 columns]


In [18]:
__label0 = label0.to_numpy()
__label1 = label1.to_numpy()[0:5300, :]
print(__label0)

[[21  6  1 ... 25 10 31]
 [11  5  2 ... 16 10 21]
 [11  4  3 ... 16  9 20]
 ...
 [12  6  1 ... 17 11 23]
 [10  5  3 ... 14  9 19]
 [ 9  5  3 ... 13  9 18]]


In [19]:
__label1.shape

(5300, 15)

In [20]:
Y0 = np.zeros(__label0.shape[0])
Y1 = np.ones(__label1.shape[0])
print(Y0.shape)
print(Y1.shape)

(5300,)
(5300,)


In [24]:
X = np.asarray(np.concatenate((__label0, __label1), axis = 0), dtype=np.float32)
Y = np.asarray(np.concatenate((Y0, Y1), axis = 0), dtype = np.float32)
print(X.shape)
print(Y.shape)

(10600, 15)
(10600,)


In [27]:
from sklearn.utils import shuffle
X, Y = shuffle(X,Y)

In [39]:
def network():
  __input = keras.Input((X.shape[1], 1))
  __conv1 = keras.layers.Conv1D(filters = 32, kernel_size = 3, activation = 'tanh')(__input)
  __dense2 = keras.layers.Dense(16, activation = 'tanh')(__conv1)
  __output = keras.layers.Dense(1, activation = 'sigmoid')(__dense2)

  model = keras.Model(inputs = __input, outputs = __output)
  return model 



model = network()
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 15, 1)]           0         
_________________________________________________________________
conv1d (Conv1D)              (None, 13, 32)            128       
_________________________________________________________________
dense_5 (Dense)              (None, 13, 16)            528       
_________________________________________________________________
dense_6 (Dense)              (None, 13, 1)             17        
Total params: 673
Trainable params: 673
Non-trainable params: 0
_________________________________________________________________


In [40]:
model.compile(loss='binary_crossentropy',
                      optimizer= keras.optimizers.Adam(lr=0.0008),
                      metrics=['accuracy'])

In [43]:
__modelVersion = 'MLP1.0'

weight_saver = tf.keras.callbacks.ModelCheckpoint('/content/drive/MyDrive/RailCop/New Files/Sakib/models/'+__modelVersion, monitor='val_accuracy', 
                                save_best_only=True, save_weights_only=False, mode= 'max')

annealer = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                              patience=5, min_lr=0.00001,mode= 'min')


hist = model.fit( x = X , 
                  y = Y, 
                  batch_size = 64,
                  epochs = 600,
                  callbacks = [weight_saver , annealer],
                  validation_split = 0.2,
                  shuffle = True,
                  verbose = 1)

Epoch 1/600
133/133 [==============================] - 1s 7ms/step - loss: 0.6469 - accuracy: 0.6283 - val_loss: 0.6478 - val_accuracy: 0.6258 - lr: 1.0000e-05
Epoch 2/600
133/133 [==============================] - 1s 7ms/step - loss: 0.6469 - accuracy: 0.6277 - val_loss: 0.6478 - val_accuracy: 0.6259 - lr: 1.0000e-05
Epoch 3/600
133/133 [==============================] - 1s 7ms/step - loss: 0.6469 - accuracy: 0.6277 - val_loss: 0.6478 - val_accuracy: 0.6262 - lr: 1.0000e-05
Epoch 4/600
133/133 [==============================] - 0s 2ms/step - loss: 0.6469 - accuracy: 0.6277 - val_loss: 0.6478 - val_accuracy: 0.6262 - lr: 1.0000e-05
Epoch 5/600
133/133 [==============================] - 0s 2ms/step - loss: 0.6469 - accuracy: 0.6276 - val_loss: 0.6478 - val_accuracy: 0.6262 - lr: 1.0000e-05
Epoch 6/600
133/133 [==============================] - 0s 2ms/step - loss: 0.6469 - accuracy: 0.6279 - val_loss: 0.6478 - val_accuracy: 0.6259 - lr: 1.0000e-05
Epoch 7/600
133/133 [===================